apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mey0468mk-python 
  janus-idp.io/tekton: mey0468mk-python
  backstage.io/kubernetes-id: mey0468mk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mey0468mk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml