apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mey0468mk-python
  janus-idp.io/tekton: mey0468mk-python
  backstage.io/kubernetes-id: mey0468mk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mey0468mk-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
