apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mey0468mk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mey0468mk-python 
  name: mey0468mk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mey0468mk-python 
